module.exports.clients = [
    'ANNAI_JEWELLERS',
    'APC',
    'ARULRAJ_HOSPITAL',
    'Asir_maruthi',
    'CHARLES_MOTORS',
    'Co_oparative_bank',
    'Holy_cross',
    'ICE_KING_OF_KINGS',
    'KANNA_SILK',
    'KING_OF_KINGS',
    'LG',
    'LIC ',
    'NILA_SEA_FOOD',
    'SARAVANA_SALT',
    'SATHYA_AGENCIES',
    'SATHYA_MOBILES',
    'SHRIRAM_TRANSPORT_FINANCE',
    'Suresh_IAS_Academy',
    'SUSEE_BAJAI',
    'Tamilnad_mercendail_bank',
    'THE_CHENNAI_SLIKS',
    'VVD'
]